### ISSUE TITLE
youtube转发后台是打钩的，但是无法播放

### ISSUE THREAD

**Issue by ajun59420** [snowie2000/livetv#1]
https://www.youtube.com/watch?v=oIgbl7t0S_w

**Comment by snowie2000** [comment]
你需要在能访问youtube的机器上运行才行，在国内机器上是不可能成功的，除非你可以勾上下面的use proxy使用代理访问

**Comment by ajun59420** [comment]
> 需要在能访问youtube的机器上运行才行，在国内机器上是不可能成功的，除非你可以勾上你下面的use proxy使用代理访问
> 
> 这个中天新闻我自己就访问过，没有任何问题

大佬，国外机，确认IP是没被墙的

**Comment by snowie2000** [comment]
在你的国外vps上执行`curl https://www.youtube.com/watch?v=oIgbl7t0S_w |grep hlsManifest`

正确的话应该返回一大堆英文和数字，如果不返回任何内容，则你的vps不支持播放这个视频

**Comment by ajun59420** [comment]
> 在你的国外vps上执行`curl https://www.youtube.com/watch?v=oIgbl7t0S_w |grep hlsManifest`
> 
> 正确的话应该返回一大堆英文和数字，如果不返回任何内容，则你的vps不支持播放这个视频，可能是有地区限制

root@debian:~# curl https://www.youtube.com/watch?v=oIgbl7t0S_w |grep hlsManifest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0ytimg.preload('https:\/\/rr11---sn-xupn5a5u5x-4wgl7.googlevideo.com\/generate_204');ytimg.preload('https:\/\/rr11---sn-xupn5a5u5x-4wgl7.googlevideo.com\/generate_204?conn2');</script><link rel="canonical" href="https://www.youtube.com/watch?v=oIgbl7t0S_w"><link rel="alternate" media="handheld" href="https://m.youtube.com/watch?v=oIgbl7t0S_w"><link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.youtube.com/watch?v=oIgbl7t0S_w"><title>【#中天新聞不斷電直播Live】 CTI中天新聞24小時HD新聞直播 │ CTITV Taiwan News HD Live｜台湾のHDニュース放送｜ 대만 HD 뉴스 방송 @中天電視CtiTv - YouTube</title><meta name="title" content="【#中天新聞不斷電直播Live】 CTI中天新聞24小時HD新聞直播 │ CTITV Taiwan News HD Live｜台湾のHDニュース放送｜ 대만 HD 뉴스 방송 @中天電視CtiTv"><meta name="description" content="#中天電視 #24小時新聞直播 #不斷更新 #新聞直播#LIVE #監督的力量在中天【超強補

**Comment by snowie2000** [comment]
我看了下返回的内容，是完全正常的。无法播放是怎么样的情况呢，如果方便的话，你可以把网址和密码信息发到我的邮箱中，邮箱在bio界面可见，不方便的话，就截图隐藏掉关键信息看一下。

**Comment by ajun59420** [comment]
直接打开URL是可以下载到M3U的，但是链接丢到播放器无法播放

**Comment by snowie2000** [comment]
试试用vlc播放。

尝试在浏览器中打开m3u中的ts地址。m3u是一个播放列表，里面应该是`https://域名/live.ts?一大堆英文`这种形式的，使用浏览器访问其中的内容试试，正常的话应该是弹出下载对话框

**Comment by ajun59420** [comment]
> 试试用vlc播放。
> 
> 尝试在浏览器中打开m3u中的ts地址。m3u是一个播放列表，里面应该是`https://域名/live.ts?一大堆英文`这种形式的，使用浏览器访问其中的内容试试，正常的话应该是弹出下载对话框

谢谢老哥，已发送邮件

**Comment by snowie2000** [comment]
已经查看了情况，需要勾选Proxy Stream使用livetv来代理流（默认情况下只代理m3u8列表）
