### ISSUE TITLE
大佬，有一事想问

### ISSUE THREAD

**Issue by weiwey** [snowie2000/livetv#2]
只能单个单个添加吗。能把将整个m3u文件放进去转发吗。

**Comment by snowie2000** [comment]
本项目的主要作用是简化php的编写，去掉php糟糕的重复解析和请求伪造，并且可以方便的整合各种来源的直播源，例如你可以转发移动iptv源，也可以同时转发php代理源，y2b源等等，并不是一个简单的m3u代理工具。

如果只是需要整个转发代理m3u的话，已经有现成的项目了：https://github.com/chinggirltube/M3U-Proxy

**Comment by weiwey** [comment]
太好了，如果能加入缓冲或者加速就更好了，因为一些源，他速度不怎么样，但是能加速他就好了。这样就看着看着不会卡。

**Comment by snowie2000** [comment]
加速的正常解决方案就是选择连接到源更快的服务器，然后通过那个服务器转发就“加速”了。
缓冲和加速都是不可能的，因为请求是实时的，直播是不断随时间更新的，你不可能缓冲不存在的片段。人家源站只提供了那么点速度，你怎么都不可能榨出更高的速度来

**Comment by weiwey** [comment]
大佬，救我。我拿到了一个PHP文件了，但是我无论用什么解析器都无法解析和推流，help me 有什么方法可以联系到你吗

**Comment by snowie2000** [comment]
你确定这个php返回的m3u8是正确的吗？如果不正确的话自然谁也无法播放

**Comment by snowie2000** [comment]
> 只能单个单个添加吗。能把将整个m3u文件放进去转发吗。

1.4版本已添加了对m3u的代理支持。
